package org.polling.pollingapp.services;

import org.polling.pollingapp.model.OptionVote;
import org.polling.pollingapp.model.Poll;
import org.polling.pollingapp.repositories.PollRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

// Business Layer is implemented here
// It indicates that a class contains business logic (e.g., calculating a total, validating a user, or processing an order)
@Service
public class PollService {

    private final PollRepository pollRepository;

    public PollService(PollRepository pollRepository) {
        this.pollRepository = pollRepository;
    }

    public Poll savePoll(Poll poll) {
        return pollRepository.save(poll);
    }


    public List<Poll> getAllPolls() {
        return pollRepository.findAll();
    }

    public Optional<Poll> getPollById(Long id) {
        return pollRepository.findById(id);
    }

    public void doVote(Long pollId, int optionIndex) {
        // Get poll from DB
        // Alternatively, one can reuse pollRepository.findById(id) as above
        Poll poll = getPollById(pollId)
                .orElseThrow(() -> new RuntimeException("Poll not found!"));

        // Extract all options
        // NOTE! getter (getOptions()) is autogenerated during compile time due to Lombok Annotation insertion
        List<OptionVote> options = poll.getOptions();

        // If index for vote invalid, throw error
        if(optionIndex < 0 || optionIndex >= options.size()) {
            throw new IllegalArgumentException("Invalid option index!");
        }

        // Get the selected option
        OptionVote selectedOption = options.get(optionIndex);

        // Increment vote for the selected option
        selectedOption.setVoteCount(selectedOption.getVoteCount() + 1);

        // Save incremented option
        pollRepository.save(poll);

    }

    public void deletePoll(Long id) {
        pollRepository.deleteById(id);
    }
}
